### ISSUE TITLE
No Checking of Rules on Gene Deletion; Ghost Gene on Reload; Causes Crash

### ISSUE THREAD

**Issue by wlongabaugh** [EmmanuelFaure76/GeNeTool#5]
1) Create gene A1
2) Create gene B1
3) Create gene B1 rule to reference A1
4) Delete gene A1; there is still a reference in the B1 rule
5) Set HPF time, create a domain
6) Step the model a few hours
7) Save out to file
8) Restart program. Load the file in. A1 has reappeared as a gene. Model only shows A1, not B1
9) Delete gene B1. Program freezes (crashes).

**Comment by kleisb** [comment]
The example cannot be replicated anymore, as the rules are checked on gene deletion.
